"""Puerto mínimo para desacoplar DIgSILENT de la lógica de aplicación."""

from pathlib import Path
from typing import Any, Mapping, Protocol


class PowerFactoryPort(Protocol):
    def find(self, class_name: str, external_id: str) -> Any | None: ...
    def create(self, class_name: str, external_id: str) -> Any: ...
    def set_attributes(self, obj: Any, values: Mapping[str, Any]) -> None: ...
    def delete(self, obj: Any) -> None: ...


class DgsImportPort(PowerFactoryPort, Protocol):
    def import_dgs(self, path: Path) -> int: ...
